server:
  port: 7777

spring:
  application:
    name: laravel-sidecar
eureka:
  client:
    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:7001/eureka},${EUREKA_URI:http://localhost:7002/eureka},${EUREKA_URI:http://localhost:7004/eureka}
       defaultZone: http://localhost:7001/eureka
    registerWithEureka: true
    fetchRegistry: false
  instance:
    preferIpAddress: true
    instance-id: laravel-sidecar

sidecar:
  port: 8000
  health-uri: http://localhost:8000/health.json